name: city_market
description: City Market — oziq-ovqat va uy-ro'zg'or buyumlari e-commerce ilovasi (MVP).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  supabase_flutter: ^2.5.0
  video_player: ^2.8.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
